dev:
	 clj -M --main cljs.main --compile quickstart.core --repl

build:
	clj -M -m cljs.main --optimizations advanced -c quickstart.core

build-node:
	clj -M -m cljs.main --target node --output-to out.js -c quickstart.core

serve:
	clj -M -m cljs.main --serve



