[package]
name = "demys"
version = "0.1.0"
authors = ["Earther <qn.khuat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.21.0"
libc = "0.2"
gimli = "0.24.0"
object = "0.25.3"
memmap = "0.7.0"
