[unstable]
# we need some bases function like: memset, memcpy
build-std-features = ["compiler-builtins-mem"]
# rebuild the core, compiler_builtints for target
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-rustos.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
